on:
  schedule: 
    - cron:  "0 0 31 * *" 
  workflow_dispatch:

name: Update data

jobs:
  updade-data:
    runs-on: ubuntu-latest
    steps:
      # that installs R on the machine
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # The R version to download (if necessary) and use.
          r-version: '3.6.3'

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest 
            any::dplyr
            any::stringr

      # to access the code inside our repository
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Import data
        run: Rscript -e 'source("dia1.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git add teste.RData
          git commit -a -m 'Data updated'
          git push 