on:
  schedule: 
    - cron:  "0 0 31 * *" 
  workflow_dispatch:

name: Update data

jobs:
  updade-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest 
            any::dplyr
            any::stringr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("dia1.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add teste.RData
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"